# Generated by Django 5.0.3 on 2024-09-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile_old_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categorias'},
        ),
    ]
